apiVersion: v1       
kind: Pod                  # Kubernetes controller objects
metadata:
  name: hello-world        # Pod name
spec:                       # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: hello             # Name of the container
    image: "ubuntu:16.04"
    command: ["/bin/echo", "hello", "world"] #Container Entrypoint